### ISSUE TITLE
Cannot find module './build/release/robotjs.node' election

### ISSUE THREAD

**Issue by diserdong** [diego3g/electron-typescript-react#72]
`Error: Cannot find module './build/Release/robotjs.node'
    at webpackMissingModule (/Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:21139:84)
    at Object../node_modules/_robotjs@0.6.0@robotjs/index.js (/Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:21139:187)
    at __webpack_require__ (/Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:27521:42)
    at /Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:27600:65
    at /Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:27772:3
    at Object.<anonymous> (/Users/diserdong/Work/workSpace/deskWork/rhino-air/.webpack/main/index.js:27775:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)`

./electron/main.js
`import robot from "robotjs"`

And I tried the suggested npm install and npm rebuild within the node_modules/robotjs directory, but the error wasn't fixed.

https://github.com/octalmage/robotjs/wiki/Electron

`npm rebuild --runtime=electron --target=13.1.2 --disturl=https://atom.io/download/atom-shell --abi=83`

node: 14.16.0
electron-rebuild: 3.2.4
electron: 13.1.2 (process.version)

**Comment by nanchengjiumeng** [comment]
so how to resolve this question?

**Comment by nanchengjiumeng** [comment]
try this: 
![image](https://user-images.githubusercontent.com/25164432/147181958-6398629c-f262-41a0-ab5c-9b6a1b6f4ba0.png)
